### ISSUE TITLE
Can you help me to make a costum DLL File to my own Backdoor menu? Thanks ^^

### ISSUE THREAD

**Issue by dominikdomex** [ProjectRebug/RebugV2-Release#7]

**Comment by JokinAce** [comment]
Lerne English du Hurensohn

**Comment by dominikdomex** [comment]
> Lerne English du Hurensohn

Danke Gleichfalls

**Comment by dominikdomex** [comment]
> Lerne English du Hurensohn

Oh kacke ... Ein wildes Jokin ist aufgetreten

**Comment by JokinAce** [comment]
Oh, kacke 0.0 Ein wildes 12 Jähriges Hurensohn ist aufgetreten

**Comment by dominikdomex** [comment]
aja

**Comment by dominikdomex** [comment]
10/10
